/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => DeepSeekAgentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian4 = require("obsidian");

// src/types.ts
var MODELS = [
  {
    id: "deepseek-v4-flash",
    label: "DeepSeek V4 Flash (\u5FEB\u901F, \u9ED8\u8BA4)",
    thinking: false
  },
  {
    id: "deepseek-v4-pro",
    label: "DeepSeek V4 Pro (\u63A8\u7406, \u6DF1\u5EA6\u601D\u8003)",
    thinking: true
  },
  {
    id: "deepseek-chat",
    label: "deepseek-chat (\u5C06\u4E8E 2026/07/24 \u5F03\u7528)",
    thinking: false,
    deprecated: "2026-07-24"
  },
  {
    id: "deepseek-reasoner",
    label: "deepseek-reasoner (\u5C06\u4E8E 2026/07/24 \u5F03\u7528)",
    thinking: true,
    deprecated: "2026-07-24"
  }
];
var DEFAULT_SETTINGS = {
  apiKey: "",
  model: "deepseek-v4-flash",
  maxTokens: 8192,
  temperature: 0.7,
  maxIterations: 20,
  enableThinking: false,
  reasoningEffort: "medium",
  systemPrompt: "\u4F60\u662F\u4E00\u4E2A Obsidian \u7B14\u8BB0\u52A9\u624B Agent\u3002\u4F60\u53EF\u4EE5\u641C\u7D22\u3001\u8BFB\u53D6\u3001\u521B\u5EFA\u3001\u7F16\u8F91\u7B14\u8BB0\u6765\u5E2E\u52A9\u7528\u6237\u5B8C\u6210\u4EFB\u52A1\u3002\n\u6BCF\u6B21\u6267\u884C\u4E00\u4E2A\u5DE5\u5177\u540E\uFF0C\u57FA\u4E8E\u7ED3\u679C\u51B3\u5B9A\u4E0B\u4E00\u6B65\u8BE5\u505A\u4EC0\u4E48\uFF0C\u76F4\u5230\u4EFB\u52A1\u5B8C\u6210\u3002\n\u4EFB\u52A1\u5B8C\u6210\u540E\u8F93\u51FA\u603B\u7ED3\u3002"
};
function getModelInfo(modelId) {
  return MODELS.find((m) => m.id === modelId) || MODELS[0];
}
function supportsThinking(modelId) {
  const info = getModelInfo(modelId);
  return info.thinking;
}

// src/DeepSeekClient.ts
var API_BASE = "https://api.deepseek.com/v1/chat/completions";
var DeepSeekClient = class {
  constructor(settings) {
    this.abortController = null;
    this.settings = settings;
  }
  /** 更新设置 */
  updateSettings(settings) {
    this.settings = settings;
  }
  /** 取消当前请求 */
  cancel() {
    var _a;
    (_a = this.abortController) == null ? void 0 : _a.abort();
  }
  /** 构建请求 body */
  buildBody(messages, tools) {
    const body = {
      model: this.settings.model,
      messages,
      max_tokens: this.settings.maxTokens,
      temperature: this.settings.temperature,
      stream: true
    };
    if (tools && tools.length > 0) {
      body.tools = tools.map((t) => ({
        type: "function",
        function: {
          name: t.name,
          description: t.description,
          parameters: t.input_schema
        }
      }));
      body.tool_choice = "auto";
    }
    if (supportsThinking(this.settings.model) && this.settings.enableThinking) {
      body.thinking = { type: "enabled" };
      body.reasoning_effort = this.settings.reasoningEffort;
    }
    return body;
  }
  /** 发送请求（无 tools） */
  async send(messages, onChunk, onThinking) {
    return this.request(messages, void 0, onChunk, onThinking);
  }
  /** 发送请求（含 tools） */
  async sendWithTools(messages, tools, onChunk, onThinking) {
    return this.request(messages, tools, onChunk, onThinking);
  }
  /** 通用请求方法 */
  async request(messages, tools, onChunk, onThinking) {
    if (!this.settings.apiKey) {
      throw new Error("\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 DeepSeek API Key");
    }
    this.abortController = new AbortController();
    const body = this.buildBody(messages, tools);
    try {
      const response = await fetch(API_BASE, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${this.settings.apiKey}`
        },
        body: JSON.stringify(body),
        signal: this.abortController.signal
      });
      if (!response.ok) {
        const errText = await response.text();
        throw new Error(`API \u9519\u8BEF ${response.status}: ${errText}`);
      }
      return this.parseStreamingResponse(response, onChunk, onThinking);
    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        throw new Error("\u8BF7\u6C42\u5DF2\u53D6\u6D88");
      }
      throw err;
    } finally {
      this.abortController = null;
    }
  }
  /** 解析 SSE 流式响应 */
  async parseStreamingResponse(response, onChunk, onThinking) {
    var _a, _b, _c, _d, _e, _f;
    const reader = (_a = response.body) == null ? void 0 : _a.getReader();
    if (!reader)
      throw new Error("\u65E0\u6CD5\u8BFB\u53D6\u54CD\u5E94\u6D41");
    const decoder = new TextDecoder();
    let buffer = "";
    let finalMessage = {
      role: "assistant",
      content: ""
    };
    while (true) {
      const { done, value } = await reader.read();
      if (done)
        break;
      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";
      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith("data: "))
          continue;
        const data = trimmed.slice(6);
        if (data === "[DONE]")
          break;
        try {
          const parsed = JSON.parse(data);
          const delta = (_c = (_b = parsed.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.delta;
          if (!delta)
            continue;
          if (delta.thinking) {
            onThinking == null ? void 0 : onThinking(delta.thinking);
          }
          if (delta.content) {
            finalMessage.content += delta.content;
            onChunk == null ? void 0 : onChunk(delta.content);
          }
          if (delta.tool_calls) {
            if (!finalMessage.tool_calls) {
              finalMessage.tool_calls = [];
            }
            for (const tc of delta.tool_calls) {
              const idx = (_d = tc.index) != null ? _d : 0;
              if (!finalMessage.tool_calls[idx]) {
                finalMessage.tool_calls[idx] = {
                  id: tc.id || `call_${idx}`,
                  type: "function",
                  function: { name: "", arguments: "" }
                };
              }
              if ((_e = tc.function) == null ? void 0 : _e.name) {
                finalMessage.tool_calls[idx].function.name += tc.function.name;
              }
              if ((_f = tc.function) == null ? void 0 : _f.arguments) {
                finalMessage.tool_calls[idx].function.arguments += tc.function.arguments;
              }
            }
          }
        } catch (e) {
        }
      }
    }
    return finalMessage;
  }
};

// src/settings.ts
var import_obsidian = require("obsidian");
var DeepSeekSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "DeepSeek Agent \u8BBE\u7F6E" });
    containerEl.createEl("h3", { text: "\u{1F50C} \u8FDE\u63A5" });
    new import_obsidian.Setting(containerEl).setName("DeepSeek API Key").setDesc("\u4ECE https://platform.deepseek.com/api_keys \u83B7\u53D6").addText(
      (text) => text.setPlaceholder("sk-xxxxxxxxxxxxxxxx").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
        this.plugin.updateClient();
      })
    );
    containerEl.createEl("h3", { text: "\u{1F9E0} \u6A21\u578B" });
    const modelSetting = new import_obsidian.Setting(containerEl).setName("\u6A21\u578B").setDesc("\u63A8\u8350\u4F7F\u7528 deepseek-v4-flash\uFF08\u5FEB\u901F\uFF09\u6216 deepseek-v4-pro\uFF08\u6DF1\u5EA6\u63A8\u7406\uFF09");
    modelSetting.addDropdown((dd) => {
      for (const m of MODELS) {
        dd.addOption(m.id, m.label);
      }
      dd.setValue(this.plugin.settings.model);
      dd.onChange(async (value) => {
        this.plugin.settings.model = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const currentModel = MODELS.find((m) => m.id === this.plugin.settings.model);
    if (currentModel == null ? void 0 : currentModel.deprecated) {
      containerEl.createEl("p", {
        text: `\u26A0\uFE0F ${currentModel.label} \u5C06\u4E8E ${currentModel.deprecated} \u5F03\u7528\uFF0C\u5EFA\u8BAE\u5207\u6362\u5230 deepseek-v4-flash \u6216 deepseek-v4-pro\u3002`,
        cls: "setting-item-description mod-warning"
      });
    }
    if (currentModel == null ? void 0 : currentModel.thinking) {
      new import_obsidian.Setting(containerEl).setName("\u542F\u7528\u601D\u8003\u6A21\u5F0F (Thinking)").setDesc("V4 Pro \u6A21\u578B\u8F93\u51FA\u524D\u4F1A\u5148\u8FDB\u884C\u5185\u90E8\u63A8\u7406\uFF0C\u8D28\u91CF\u66F4\u9AD8\u4F46\u901F\u5EA6\u8F83\u6162").addToggle(
        (tg) => tg.setValue(this.plugin.settings.enableThinking).onChange(async (value) => {
          this.plugin.settings.enableThinking = value;
          await this.plugin.saveSettings();
          this.display();
        })
      );
      if (this.plugin.settings.enableThinking) {
        new import_obsidian.Setting(containerEl).setName("\u63A8\u7406\u6DF1\u5EA6 (Reasoning Effort)").setDesc("low=\u5FEB\u901F/medium=\u9002\u4E2D/high=\u6DF1\u5EA6\uFF0C\u8D8A\u9AD8\u8D8A\u8017\u65F6").addDropdown((dd) => {
          dd.addOption("low", "low (\u5FEB\u901F)");
          dd.addOption("medium", "medium (\u9002\u4E2D)");
          dd.addOption("high", "high (\u6DF1\u5EA6)");
          dd.setValue(this.plugin.settings.reasoningEffort);
          dd.onChange(async (value) => {
            this.plugin.settings.reasoningEffort = value;
            await this.plugin.saveSettings();
          });
        });
      }
    } else {
      if (this.plugin.settings.enableThinking) {
        this.plugin.settings.enableThinking = false;
        this.plugin.saveSettings();
      }
    }
    containerEl.createEl("h3", { text: "\u2699\uFE0F \u751F\u6210\u53C2\u6570" });
    new import_obsidian.Setting(containerEl).setName("Temperature").setDesc("\u751F\u6210\u968F\u673A\u6027 (0-2, \u9ED8\u8BA4 0.7)").addSlider(
      (sl) => sl.setLimits(0, 2, 0.1).setValue(this.plugin.settings.temperature).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.temperature = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6700\u5927 Token \u6570").setDesc("\u5355\u6B21\u56DE\u590D\u7684\u6700\u5927\u957F\u5EA6").addText(
      (text) => text.setPlaceholder("8192").setValue(String(this.plugin.settings.maxTokens)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxTokens = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("h3", { text: "\u{1F916} Agent \u884C\u4E3A" });
    new import_obsidian.Setting(containerEl).setName("\u6700\u5927\u8FED\u4EE3\u6B21\u6570").setDesc("Agent \u5728\u6267\u884C\u591A\u6B65\u4EFB\u52A1\u65F6\u7684\u6700\u5927\u5DE5\u5177\u8C03\u7528\u8F6E\u6570").addText(
      (text) => text.setPlaceholder("20").setValue(String(this.plugin.settings.maxIterations)).onChange(async (value) => {
        const num = parseInt(value);
        if (!isNaN(num) && num > 0) {
          this.plugin.settings.maxIterations = num;
          await this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u7CFB\u7EDF\u63D0\u793A\u8BCD").setDesc("\u5B9A\u4E49 Agent \u7684\u884C\u4E3A\u548C\u89D2\u8272").addTextArea(
      (ta) => ta.setPlaceholder(DEFAULT_SETTINGS.systemPrompt).setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("hr");
    containerEl.createEl("p", {
      text: "\u{1F4A1} \u5728\u547D\u4EE4\u9762\u677F\u4E2D\u8FD0\u884C\u300CDeepSeek Agent: \u6253\u5F00\u300D\u6253\u5F00\u804A\u5929\u9762\u677F\u3002",
      cls: "setting-item-description"
    });
    new import_obsidian.Setting(containerEl).setName("\u91CD\u7F6E\u8BBE\u7F6E").setDesc("\u6062\u590D\u51FA\u5382\u8BBE\u7F6E").addButton(
      (btn) => btn.setButtonText("\u91CD\u7F6E").setWarning().onClick(async () => {
        this.plugin.settings = { ...DEFAULT_SETTINGS };
        await this.plugin.saveSettings();
        this.display();
      })
    );
  }
};

// src/views/ChatView.ts
var import_obsidian3 = require("obsidian");

// src/Agent.ts
var Agent = class {
  constructor(client, tools, settings, callbacks) {
    this.messages = [];
    this.iterationCount = 0;
    this.client = client;
    this.tools = tools;
    this.settings = settings;
    this.callbacks = callbacks;
  }
  /** 运行 Agent */
  async run(task) {
    this.messages = [];
    this.iterationCount = 0;
    this.messages.push({
      role: "system",
      content: this.settings.systemPrompt
    });
    this.messages.push({
      role: "user",
      content: task
    });
    await this.loop();
  }
  /** 追加用户消息（多轮对话） */
  async continue(userMessage) {
    this.iterationCount = 0;
    this.messages.push({
      role: "user",
      content: userMessage
    });
    await this.loop();
  }
  /** Agent 主循环 */
  async loop() {
    const toolDefinitions = this.tools.getDefinitions();
    let finalContent = "";
    while (this.iterationCount < this.settings.maxIterations) {
      this.iterationCount++;
      try {
        const response = await this.client.sendWithTools(
          this.messages,
          toolDefinitions,
          // 文本流式回调
          (text) => {
            this.callbacks.onThinking(text);
          },
          // 推理过程回调（V4 Pro/R1 独有）
          (text) => {
            this.callbacks.onReasoning(text);
          }
        );
        this.messages.push(response);
        if (response.tool_calls && response.tool_calls.length > 0) {
          for (const tc of response.tool_calls) {
            await this.handleToolCall(tc);
          }
          continue;
        }
        finalContent = response.content;
        this.callbacks.onDone(response.content);
        return;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        this.callbacks.onError(msg);
        return;
      }
    }
    this.callbacks.onDone(
      `\u5DF2\u8FBE\u5230\u6700\u5927\u8FED\u4EE3\u6B21\u6570 (${this.settings.maxIterations})\uFF0C\u4EFB\u52A1\u53EF\u80FD\u672A\u5B8C\u6210\u3002
${finalContent}`
    );
  }
  /** 处理单个工具调用 */
  async handleToolCall(tc) {
    const name = tc.function.name;
    let args = {};
    try {
      args = JSON.parse(tc.function.arguments);
    } catch (e) {
      args = {};
    }
    this.callbacks.onToolCall(name, tc.function.arguments);
    const result = await this.tools.execute(name, args);
    this.callbacks.onToolResult(name, result.output);
    this.messages.push({
      role: "tool",
      content: result.output,
      tool_call_id: tc.id,
      name
    });
  }
  /** 重置 Agent 状态 */
  reset() {
    this.messages = [];
    this.iterationCount = 0;
  }
};

// src/tools/VaultTools.ts
var import_obsidian2 = require("obsidian");
var VaultTools = class {
  constructor(app) {
    this.app = app;
  }
  /** 获取所有工具定义（发给 DeepSeek 用） */
  getDefinitions() {
    return [
      {
        name: "search_notes",
        description: "\u641C\u7D22 vault \u4E2D\u7684\u7B14\u8BB0\u5185\u5BB9\u3002\u8FD4\u56DE\u5339\u914D\u7684\u6587\u4EF6\u8DEF\u5F84\u548C\u6458\u8981\u7247\u6BB5\u3002\u652F\u6301\u4E2D\u6587\u641C\u7D22\u3002",
        input_schema: {
          type: "object",
          properties: {
            query: {
              type: "string",
              description: "\u641C\u7D22\u5173\u952E\u8BCD"
            },
            maxResults: {
              type: "number",
              description: "\u6700\u5927\u8FD4\u56DE\u6570\uFF08\u9ED8\u8BA4 10\uFF09"
            }
          },
          required: ["query"]
        }
      },
      {
        name: "read_note",
        description: "\u8BFB\u53D6\u4E00\u7BC7\u7B14\u8BB0\u7684\u5B8C\u6574\u5185\u5BB9",
        input_schema: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "\u7B14\u8BB0\u8DEF\u5F84\uFF08\u5982 \u65E5\u8BB0/2024-01-01.md\uFF09"
            }
          },
          required: ["path"]
        }
      },
      {
        name: "write_note",
        description: "\u521B\u5EFA\u65B0\u7B14\u8BB0\u6216\u8986\u5199\u5DF2\u6709\u7B14\u8BB0",
        input_schema: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "\u7B14\u8BB0\u8DEF\u5F84\uFF08\u5982 \u65E5\u8BB0/2024-01-01.md\uFF09"
            },
            content: {
              type: "string",
              description: "\u7B14\u8BB0\u5185\u5BB9\uFF08Markdown \u683C\u5F0F\uFF09"
            },
            overwrite: {
              type: "boolean",
              description: "\u5982\u679C\u6587\u4EF6\u5DF2\u5B58\u5728\uFF0C\u662F\u5426\u8986\u5199\uFF08\u9ED8\u8BA4 false\uFF09"
            }
          },
          required: ["path", "content"]
        }
      },
      {
        name: "patch_note",
        description: "\u7F16\u8F91\u7B14\u8BB0\u7684\u67D0\u4E00\u6BB5\u5185\u5BB9\uFF08\u641C\u7D22\u66FF\u6362\uFF09",
        input_schema: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "\u7B14\u8BB0\u8DEF\u5F84"
            },
            search: {
              type: "string",
              description: "\u8981\u67E5\u627E\u7684\u6587\u672C\uFF08\u5FC5\u987B\u552F\u4E00\uFF09"
            },
            replace: {
              type: "string",
              description: "\u66FF\u6362\u540E\u7684\u6587\u672C"
            }
          },
          required: ["path", "search", "replace"]
        }
      },
      {
        name: "list_notes",
        description: "\u5217\u4E3E vault \u4E2D\u67D0\u4E2A\u76EE\u5F55\u4E0B\u7684\u7B14\u8BB0\u548C\u5B50\u76EE\u5F55",
        input_schema: {
          type: "object",
          properties: {
            path: {
              type: "string",
              description: "\u76EE\u5F55\u8DEF\u5F84\uFF08\u9ED8\u8BA4 vault \u6839\u76EE\u5F55\uFF09"
            }
          },
          required: []
        }
      },
      {
        name: "get_active_note",
        description: "\u83B7\u53D6\u5F53\u524D\u5728\u7F16\u8F91\u5668\u4E2D\u6253\u5F00\u7684\u7B14\u8BB0\u8DEF\u5F84\u548C\u5185\u5BB9",
        input_schema: {
          type: "object",
          properties: {},
          required: []
        }
      }
    ];
  }
  /** 执行工具调用 */
  async execute(name, args) {
    try {
      switch (name) {
        case "search_notes":
          return await this.searchNotes(args.query, args.maxResults);
        case "read_note":
          return await this.readNote(args.path);
        case "write_note":
          return await this.writeNote(
            args.path,
            args.content,
            args.overwrite
          );
        case "patch_note":
          return await this.patchNote(
            args.path,
            args.search,
            args.replace
          );
        case "list_notes":
          return await this.listNotes(args.path);
        case "get_active_note":
          return await this.getActiveNote();
        default:
          return { success: false, output: `\u672A\u77E5\u5DE5\u5177: ${name}` };
      }
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, output: `\u6267\u884C\u51FA\u9519: ${msg}` };
    }
  }
  // ── 工具实现 ──
  async searchNotes(query, maxResults = 10) {
    const vault = this.app.vault;
    const files = vault.getMarkdownFiles();
    const results = [];
    const q = query.toLowerCase();
    for (const file of files) {
      if (results.length >= maxResults)
        break;
      try {
        const content = await vault.read(file);
        const lines = content.split("\n");
        for (let i = 0; i < lines.length; i++) {
          if (lines[i].toLowerCase().includes(q)) {
            const snippet = lines.slice(Math.max(0, i - 1), i + 2).join("\n").trim();
            results.push({
              path: file.path,
              snippet: snippet.slice(0, 200)
            });
            break;
          }
        }
      } catch (e) {
      }
    }
    if (results.length === 0) {
      return { success: true, output: `\u672A\u627E\u5230\u5305\u542B"${query}"\u7684\u7B14\u8BB0` };
    }
    const output = results.map((r) => `\u{1F4C4} ${r.path}
\`\`\`
${r.snippet}
\`\`\``).join("\n---\n");
    return { success: true, output };
  }
  async readNote(path) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file || !(file instanceof import_obsidian2.TFile)) {
      return { success: false, output: `\u6587\u4EF6\u4E0D\u5B58\u5728: ${path}` };
    }
    const content = await this.app.vault.read(file);
    return {
      success: true,
      output: `\u{1F4C4} ${path}

${content}`
    };
  }
  async writeNote(path, content, overwrite = false) {
    const vault = this.app.vault;
    const existing = vault.getAbstractFileByPath(path);
    if (existing && existing instanceof import_obsidian2.TFile) {
      if (!overwrite) {
        return {
          success: false,
          output: `\u6587\u4EF6\u5DF2\u5B58\u5728: ${path}\u3002\u5982\u9700\u8986\u5199\u8BF7\u8BBE\u7F6E overwrite=true`
        };
      }
      await vault.modify(existing, content);
      return { success: true, output: `\u2705 \u5DF2\u66F4\u65B0: ${path}` };
    }
    const parentPath = path.contains("/") ? path.slice(0, path.lastIndexOf("/")) : "";
    if (parentPath) {
      const parent = vault.getAbstractFileByPath(parentPath);
      if (!parent || !(parent instanceof import_obsidian2.TFolder)) {
        await vault.createFolder(parentPath);
      }
    }
    await vault.create(path, content);
    return { success: true, output: `\u2705 \u5DF2\u521B\u5EFA: ${path}` };
  }
  async patchNote(path, search, replace) {
    const file = this.app.vault.getAbstractFileByPath(path);
    if (!file || !(file instanceof import_obsidian2.TFile)) {
      return { success: false, output: `\u6587\u4EF6\u4E0D\u5B58\u5728: ${path}` };
    }
    const content = await this.app.vault.read(file);
    const idx = content.indexOf(search);
    if (idx === -1) {
      return {
        success: false,
        output: `\u672A\u5728 ${path} \u4E2D\u627E\u5230:
"""${search}"""`
      };
    }
    const lastIdx = content.lastIndexOf(search);
    if (idx !== lastIdx) {
      return {
        success: false,
        output: `\u641C\u7D22\u6587\u672C\u5728 ${path} \u4E2D\u51FA\u73B0\u591A\u6B21\uFF0C\u8BF7\u63D0\u4F9B\u66F4\u7CBE\u786E\u7684\u5339\u914D`
      };
    }
    const newContent = content.replace(search, replace);
    await this.app.vault.modify(file, newContent);
    return { success: true, output: `\u2705 \u5DF2\u66F4\u65B0 ${path}` };
  }
  async listNotes(path) {
    const target = path ? this.app.vault.getAbstractFileByPath(path) : this.app.vault.getRoot();
    if (!target) {
      return { success: false, output: `\u76EE\u5F55\u4E0D\u5B58\u5728: ${path}` };
    }
    const folder = target instanceof import_obsidian2.TFolder ? target : target.parent;
    if (!folder) {
      return { success: false, output: "\u65E0\u6CD5\u83B7\u53D6\u76EE\u5F55\u4FE1\u606F" };
    }
    const items = folder.children.filter((c) => c instanceof import_obsidian2.TFile || c instanceof import_obsidian2.TFolder).map((c) => {
      const icon = c instanceof import_obsidian2.TFolder ? "\u{1F4C1}" : "\u{1F4C4}";
      return `${icon} ${c.name}`;
    }).join("\n");
    const folderPath = folder.path || "/";
    return {
      success: true,
      output: `\u{1F4C2} ${folderPath}
${items}`
    };
  }
  async getActiveNote() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
    if (!view) {
      return { success: false, output: "\u5F53\u524D\u6CA1\u6709\u6253\u5F00\u7684\u7B14\u8BB0" };
    }
    const file = view.file;
    if (!file) {
      return { success: false, output: "\u65E0\u6CD5\u83B7\u53D6\u5F53\u524D\u7B14\u8BB0" };
    }
    const content = await this.app.vault.read(file);
    return {
      success: true,
      output: `\u{1F4C4} ${file.path}

${content}`
    };
  }
};

// src/views/ChatView.ts
var VIEW_TYPE = "deepseek-agent-chat";
var ChatView = class extends import_obsidian3.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.isRunning = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "DeepSeek Agent";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("deepseek-agent-container");
    const header = container.createDiv("deepseek-agent-header");
    header.createEl("h3", { text: "\u{1F916} DeepSeek Agent" });
    this.statusEl = header.createSpan("deepseek-agent-status");
    this.statusEl.setText("\u5C31\u7EEA");
    this.abortBtn = header.createEl("button", "deepseek-agent-abort-btn");
    this.abortBtn.setText("\u2715 \u505C\u6B62");
    this.abortBtn.addClass("deepseek-agent-hidden");
    this.abortBtn.onClickEvent(() => {
      this.isRunning = false;
      this.abortBtn.addClass("deepseek-agent-hidden");
      this.statusEl.setText("\u5DF2\u505C\u6B62");
    });
    this.messagesEl = container.createDiv("deepseek-agent-messages");
    this.addWelcomeMessage();
    const inputArea = container.createDiv("deepseek-agent-input-area");
    this.inputEl = inputArea.createEl("textarea", "deepseek-agent-input");
    this.inputEl.setAttr("rows", "3");
    this.inputEl.setAttr("placeholder", "\u8F93\u5165\u4EFB\u52A1\u2026\n\u4F8B\u5982\uFF1A\u628A\u8FD9\u5468\u65E5\u8BB0\u603B\u7ED3\u6210\u5468\u62A5");
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    const btnRow = inputArea.createDiv("deepseek-agent-btn-row");
    this.sendBtn = btnRow.createEl("button", "deepseek-agent-send-btn");
    this.sendBtn.setText("\u25B6 \u53D1\u9001");
    this.sendBtn.onClickEvent(() => this.sendMessage());
    const quickRow = container.createDiv("deepseek-agent-quick-row");
    const quickBtns = [
      { text: "\u{1F4CB} \u5F53\u524D\u7B14\u8BB0\u603B\u7ED3", action: "\u603B\u7ED3\u5F53\u524D\u8FD9\u7BC7\u7B14\u8BB0\u7684\u5185\u5BB9\u8981\u70B9" },
      { text: "\u{1F4CA} \u672C\u5468\u6C47\u603B", action: "\u67E5\u627E\u672C\u5468\u6240\u6709\u65E5\u8BB0\uFF0C\u6C47\u603B\u6210\u4E00\u4EFD\u5468\u62A5" },
      { text: "\u{1F50D} \u641C\u7D22\u95EA\u5FF5", action: "\u641C\u7D22\u6240\u6709\u672A\u6574\u7406\u7684\u95EA\u5FF5\u7B14\u8BB0" }
    ];
    for (const qb of quickBtns) {
      const btn = quickRow.createEl("button", "deepseek-agent-quick-btn");
      btn.setText(qb.text);
      btn.onClickEvent(() => {
        this.inputEl.value = qb.action;
        this.sendMessage();
      });
    }
  }
  async onClose() {
  }
  /** 发送消息 */
  async sendMessage() {
    const text = this.inputEl.value.trim();
    if (!text || this.isRunning)
      return;
    this.inputEl.value = "";
    this.isRunning = true;
    this.abortBtn.removeClass("deepseek-agent-hidden");
    this.sendBtn.setText("\u23F3 \u6267\u884C\u4E2D\u2026");
    this.statusEl.setText("\u601D\u8003\u4E2D\u2026");
    this.addMessageEl("user", text);
    try {
      if (!this.plugin.settings.apiKey) {
        this.addMessageEl(
          "error",
          "\u274C \u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u586B\u5199 DeepSeek API Key\n`\u8BBE\u7F6E \u2192 \u63D2\u4EF6\u9009\u9879 \u2192 DeepSeek Agent`"
        );
        this.isRunning = false;
        this.sendBtn.setText("\u25B6 \u53D1\u9001");
        this.abortBtn.addClass("deepseek-agent-hidden");
        this.statusEl.setText("\u5C31\u7EEA");
        return;
      }
      const client = new DeepSeekClient(this.plugin.settings);
      const tools = new VaultTools(this.plugin.app);
      this.agent = new Agent(
        client,
        tools,
        this.plugin.settings,
        this.createCallbacks()
      );
      await this.agent.run(text);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.addMessageEl("error", `\u274C ${msg}`);
    } finally {
      this.isRunning = false;
      this.sendBtn.setText("\u25B6 \u53D1\u9001");
      this.abortBtn.addClass("deepseek-agent-hidden");
      this.statusEl.setText("\u5C31\u7EEA");
    }
  }
  /** 创建回调 */
  createCallbacks() {
    let currentAssistantEl = null;
    let currentAssistantContent = "";
    let currentReasoningEl = null;
    return {
      onThinking: (text) => {
        if (!currentAssistantEl) {
          currentAssistantEl = this.addMessageEl("assistant", "");
          currentAssistantContent = "";
        }
        currentAssistantContent += text;
        currentAssistantEl.setText(currentAssistantContent);
      },
      onReasoning: (text) => {
        if (!currentReasoningEl) {
          currentReasoningEl = this.messagesEl.createDiv(
            "deepseek-agent-reasoning"
          );
          const header = currentReasoningEl.createDiv(
            "deepseek-agent-reasoning-header"
          );
          header.setText("\u{1F9E0} \u63A8\u7406\u8FC7\u7A0B");
          const body = currentReasoningEl.createDiv(
            "deepseek-agent-reasoning-body"
          );
          body.setText(text);
          this.scrollToBottom();
        } else {
          const body = currentReasoningEl.querySelector(
            ".deepseek-agent-reasoning-body"
          );
          if (body) {
            body.setText(
              body.textContent + text
            );
          }
        }
      },
      onToolCall: (name, args) => {
        currentAssistantEl = null;
        currentAssistantContent = "";
        currentReasoningEl = null;
        this.addToolCallEl(name, args);
      },
      onToolResult: (name, result) => {
        const preview = result.length > 150 ? result.slice(0, 150) + "\u2026" : result;
        this.addToolResultEl(name, preview);
      },
      onMessage: (text) => {
        this.addMessageEl("assistant", text);
      },
      onError: (error) => {
        this.addMessageEl("error", `\u274C ${error}`);
      },
      onDone: (summary) => {
        this.statusEl.setText("\u2705 \u5B8C\u6210");
      }
    };
  }
  /** 添加消息气泡 */
  addMessageEl(role, content) {
    const el = this.messagesEl.createDiv(
      `deepseek-agent-msg deepseek-agent-msg-${role}`
    );
    el.setText(content);
    this.scrollToBottom();
    return el;
  }
  /** 添加工具调用指示 */
  addToolCallEl(name, args) {
    const el = this.messagesEl.createDiv("deepseek-agent-tool-call");
    const header = el.createDiv("deepseek-agent-tool-header");
    header.setText(`\u{1F527} \u8C03\u7528: ${name}`);
    const detail = el.createDiv("deepseek-agent-tool-detail");
    try {
      const parsed = JSON.parse(args);
      detail.setText(JSON.stringify(parsed, null, 2));
    } catch (e) {
      detail.setText(args);
    }
    this.scrollToBottom();
  }
  /** 添加工具结果指示 */
  addToolResultEl(name, result) {
    const el = this.messagesEl.createDiv("deepseek-agent-tool-result");
    el.setText(`\u{1F4E5} ${name} \u2192 ${result}`);
    this.scrollToBottom();
  }
  /** 欢迎消息 */
  addWelcomeMessage() {
    const el = this.messagesEl.createDiv(
      "deepseek-agent-msg deepseek-agent-msg-system"
    );
    el.innerHTML = `
\u{1F44B} \u4F60\u597D\uFF01\u6211\u662F DeepSeek Agent\u3002

\u6211\u53EF\u4EE5\u5E2E\u4F60:
- \u{1F4D6} <b>\u603B\u7ED3\u7B14\u8BB0</b> \u2014 "\u603B\u7ED3\u5F53\u524D\u7B14\u8BB0"
- \u{1F4CA} <b>\u751F\u6210\u5468\u62A5</b> \u2014 "\u628A\u672C\u5468\u65E5\u8BB0\u6C47\u603B\u6210\u5468\u62A5"
- \u{1F50D} <b>\u641C\u7D22\u5185\u5BB9</b> \u2014 "\u627E\u5230\u5173\u4E8EXX\u7684\u7B14\u8BB0"
- \u270F\uFE0F <b>\u6279\u91CF\u7F16\u8F91</b> \u2014 "\u628A\u6807\u7B7E #draft \u6539\u6210 #published"
- \u{1F4DD} <b>\u521B\u5EFA\u5185\u5BB9</b> \u2014 "\u6839\u636E\u7B14\u8BB0 X \u751F\u6210\u4E00\u7BC7\u535A\u5BA2"

\u8BD5\u8BD5\u8F93\u5165\u4EFB\u52A1\uFF0C\u6216\u8005\u70B9\u4E0B\u9762\u7684\u5FEB\u6377\u6309\u94AE \u{1F447}
		`.trim();
  }
  scrollToBottom() {
    requestAnimationFrame(() => {
      this.messagesEl.scrollTo({
        top: this.messagesEl.scrollHeight,
        behavior: "smooth"
      });
    });
  }
};

// main.ts
var DeepSeekAgentPlugin = class extends import_obsidian4.Plugin {
  constructor(app, manifest) {
    super(app, manifest);
    this.settings = { ...DEFAULT_SETTINGS };
    this.client = new DeepSeekClient(this.settings);
  }
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE, (leaf) => new ChatView(leaf, this));
    this.addCommand({
      id: "open-deepseek-agent",
      name: "\u6253\u5F00 DeepSeek Agent",
      callback: () => this.openChatView()
    });
    this.addCommand({
      id: "deepseek-summarize",
      name: "Agent: \u603B\u7ED3\u5F53\u524D\u7B14\u8BB0",
      callback: () => this.quickTask("\u603B\u7ED3\u5F53\u524D\u8FD9\u7BC7\u7B14\u8BB0\u7684\u5185\u5BB9\u8981\u70B9")
    });
    this.addCommand({
      id: "deepseek-ask-selection",
      name: "Agent: \u89E3\u91CA\u9009\u4E2D\u7684\u6587\u672C",
      editorCallback: (editor) => {
        const selected = editor.getSelection();
        if (selected) {
          this.quickTask(`\u89E3\u91CA\u4EE5\u4E0B\u5185\u5BB9:

${selected}`);
        }
      }
    });
    this.addSettingTab(new DeepSeekSettingTab(this.app, this));
    this.addRibbonIcon("bot", "DeepSeek Agent", () => {
      this.openChatView();
    });
    this.registerRestoreView();
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE);
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, data);
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  updateClient() {
    this.client.updateSettings(this.settings);
  }
  /** 打开聊天侧边栏 */
  async openChatView() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE);
    if (existing.length > 0) {
      workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = workspace.getRightLeaf(false);
    if (leaf) {
      await leaf.setViewState({
        type: VIEW_TYPE,
        active: true
      });
      workspace.revealLeaf(leaf);
    }
  }
  /** 快速任务（打开面板并发送消息） */
  async quickTask(task) {
    await this.openChatView();
    setTimeout(() => {
      const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
      if (leaves.length > 0) {
        const view = leaves[0].view;
        if (view instanceof ChatView) {
        }
      }
    }, 300);
  }
  /** 注册视图恢复 */
  registerRestoreView() {
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
      })
    );
  }
};
